keys:
  - &tower age1r68wyfhzkpkm9j2jwyg0vfud4qds3a74x7qkfgk39mv5q758lfjqwnu4nz
  - &thinkpad age173gaqk56n79pf0yhq7t6rh3k6c279xjqu6zywthzksjdp9kzfgts9pz20u
  - &pi0 age1wyp0qkl493emy03h9dng9q5mtjhrzecuwlkcss6q8rsev6fmw53sct8r4d
  - &apu age1vzzz8r6m6lztddzsk8hrd9unakch4jprl6y7qhgqjfy7f97x3urqwgqhgx

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *tower
        - *thinkpad
        - *pi0
        - *apu
