keys:
  - &host_tower age1r68wyfhzkpkm9j2jwyg0vfud4qds3a74x7qkfgk39mv5q758lfjqwnu4nz
  - &host_thinkpad age173gaqk56n79pf0yhq7t6rh3k6c279xjqu6zywthzksjdp9kzfgts9pz20u
  - &host_mention age10zq729g0z50ln4v2c3l5msk0zpxwe2pe62ayyz9ht5y9ah6zfd4slcynec

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *host_tower
        - *host_thinkpad
        - *host_mention
