name: CI

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@v24

      - name: Install Mention deploy key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MENTION_SSH_KEY  }}

      - name: Flake Check
        run: nix flake check

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
