name: CI

on:
  pull_request:
  push:
    paths:
    - '**.nix'
    - flake.lock

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@v19

      - name: Fmt
        run: nix fmt . -- --check

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@v19

      - name: Add mention deploy key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.MENTION_SSH_KEY }}'

      - name: Flake Check
        run: nix flake check