name: CI

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@V27

      - name: Flake Check
        run: nix flake check

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v7
        with:
          nixpkgs-keys: nixpkgs,unstable
