tailscale_auth_key: ENC[AES256_GCM,data:C3prqyjpuRPbkRb8pftUDUsynp906KmGNsg13Ti0Xsm/8T0pMaBJKF+XHa0dCTsoSNhnAAMIPN4=,iv:8oUFdYtx6S2nZJ4LPT4d/DTVEO/L8GV+savBHX9ZpkU=,tag:KM0y6jiLuYZGn3iZeR4DZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173gaqk56n79pf0yhq7t6rh3k6c279xjqu6zywthzksjdp9kzfgts9pz20u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0pXMXZuQ1hzWitFYXZK
            MU1UY2J3OFd5dzQ2RHRsaDlTV2pXTTJGVVNZCnN4SkYvOGdDbGx6N1k0SGVSRitl
            QmQvSGFUVnhzazl1NWJyMVdLYldqcm8KLS0tIGVHd0hhQUJoUXpmZTM4dUI1a2hz
            Y1k1SGJ2SGdDTlB4NTdJZDY1RXdaZ3cKuZ0FoAYUuudO7ynbRjkVAbwkyb7a8+9J
            r8JM/DK6NGhrtEfA+u61jJYbQInQrITgTOeX5HffwjpTH4VLYDHgbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-01T11:51:50Z"
    mac: ENC[AES256_GCM,data:H2LEaOwEFawOL+ZjCZJAfg6Qx9zqYl0IIDHcNK71qjLkIRmHMsxc2GA7EPv8mjpVYHpzBNngd/AI0gpEGGyaPv5KXZ+ZjbRlNFVHgrQYzT2uo0ftR2mD5EvpJfKVdmkaCckAhj/QgezbhawMLlrr+l3mnfQ4DqsrPF+NU6cGxj0=,iv:E0QVuow82+DOC7vNkTWuRil/pjRkjoGajVO6ZX0ofLA=,tag:sFJDMEUy1k8dVdT44OK0Zg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
