home_wifi_network_password: ENC[AES256_GCM,data:3r4jHN7rfyf4pu/PKh9z2xAQ,iv:MT9rrcVphnc7JCgwAKtMvW+NtETkx1F5Rs7h/xNXBB4=,tag:VgVSoGKJ7NbSNjRrwWfGEA==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:d8f6VBUZa6QbLMV+2wRoYZV+FU+S07JknSFySZAtNKfxcCE+kFC8OmIUrqIAw06e6lLUxxfyjT8=,iv:kVDNWWD19RJS9ptl1GWYP7mcY4oOSbHfsDzfGKNZ+SE=,tag:ABMrwwZtR1TaWurfHi2mfA==,type:str]
cellar_backups_key_id: ENC[AES256_GCM,data:L3bV9Ab8jTNe6OU20QZdAy1XfwM=,iv:Gnb8N3PRGlq/UxqnhMPyOjbG4oLTJbx9eSBsNlhSkG0=,tag:NO+h75E8DMuTq0unzY0n4A==,type:str]
cellar_backups_key_secret: ENC[AES256_GCM,data:gddEMWnD+LlyO4/ZEvgcfeT6jR9AebFHps1Ql2gT4DUn5A3v+U+HGw==,iv:12mrAieKwmlQH2FU5/mVikL/G4WtBK554Hft3CIxogI=,tag:0oIGxAkHa9zwza0gu1wNhw==,type:str]
github_personal_token: ENC[AES256_GCM,data:Ajofm2Roz2NdIsAYnD3PBSD2ENJaZLNewWrm1NlkyefnSk2k4qaGqQ==,iv:p2neATB+O9lc6yxSOu+UAYmSXF1u3266on+1cLVtuWw=,tag:25rxtqxAuu/77wsTGV4fdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r68wyfhzkpkm9j2jwyg0vfud4qds3a74x7qkfgk39mv5q758lfjqwnu4nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRTNsUGgwVlU5QXZ5U3lE
            ZGZhblhhcCtNMWlIVVhtSUJhZG5BTWJrVkMwCjEweXJjMk1XdlVkbUJiblJzRkVY
            TkNyRTRVeUdLcFJrWnNhZVB2cnpiQjQKLS0tIFpvTWRBY1ZzWTFmdEhTbzE3ZG42
            MFVkM1ZFVTFVd05UN1FTbSs3TkRjMXMKZl0CZffTM/d4IgRVhWTKdUYcjH1SkgOI
            mN+HILsyyu/Dl/Oc+0qfTlf1+Mclz9io1Tnv8JUfIxGU4iq/o8VPIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age173gaqk56n79pf0yhq7t6rh3k6c279xjqu6zywthzksjdp9kzfgts9pz20u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmJMRlZHc00xanUwYytS
            VlVuSStLbHF1Y1JRWmxSUGJHOEdES0QvOTJnClpwZlNhV2lBZ0RVdHZxQkJWT1Fm
            TVRmdExUK1llZEZLdjIrNHQ4N2FaWmcKLS0tIEFSUitWU0U4Y2t2cWlzN0tSaTkw
            ZnRRcE8wRkJWTGdhNFdhN0xmdlVkcm8KDI85b4rTLOrtOb+a8+AiO4jOAfOToe+V
            MBJnDGf9Fmz4HX2nmuod8fNOXqZsxayceE/6QNTSLgsqvSLgTSTt2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10zq729g0z50ln4v2c3l5msk0zpxwe2pe62ayyz9ht5y9ah6zfd4slcynec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOE96RUFXWnFYZUFiYXBw
            Zk5hTWVaTlk4UXJQdmVyQ08vaDltWEk0M1g4ClVnc2dXVTNaaHljbGV1SG83cmlY
            S2hIZ2g4UXdoRFU4MVFwSHA1MFhXSUUKLS0tIDNMTlRYQnNSc0xxQU1Da0Y2emRR
            ODhQaGkxemtxbUFibXREUVVxZzRMQk0KJs056WOyoPE8czjknEyxVFG89DRGP4HY
            0BSbg7h5fo88Lj4F1RmdUC4eyAoFu9iUpiMAKiLSSnin33XN0Ku4Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wyp0qkl493emy03h9dng9q5mtjhrzecuwlkcss6q8rsev6fmw53sct8r4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZU95NnpybGI0VDl4eXNP
            QklDSjdQWjJiRDZUL2o5ejljNnhBb25mZzBZCmxaSGh1dy8rODI0b2Y3ZndrS1NC
            OXBYQ0QyWW10ek9Malh6dGJhRElVS0kKLS0tIG01NzNnYjJ4OWlIWThzNmJnL292
            ZklwVEtsUUVTU2VBeWo5Mnlkc2ZWdkUKzTDk5uHddU4pavdOtPgUb9s8QxC/rkD5
            JqAkoOY8KDVmmUyPtzr/iEkh//YvrlKC3TdrEmmlKVmsMKU459BGVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vzzz8r6m6lztddzsk8hrd9unakch4jprl6y7qhgqjfy7f97x3urqwgqhgx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycDA0TG5IOWlZU3hGN1U3
            N3VzbXpCQ1VER2E4M2kzbENZMUgwdDF5SEJvClAwdTRkMzZlanV4TUxqc1NZTEp0
            ZTBwTFA5aE9MV1AxNkw0cXBONUdYaU0KLS0tIDc4VDVMaW8wREFZaXExNDZ2SFlr
            TVQzVHhSU1R6bEU0cHZRZXFEbzlXWkUKtZ+gg5kaPTsj7l3g4PtjpOG/KBCzKGSU
            4CdCc0TZYQyupHOaK5uDwS47ntaZ4GbBif5lNximtnEIeSLdFxgxjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T08:21:18Z"
    mac: ENC[AES256_GCM,data:64jLoekDXfMYtdbwuK4jcJTrM1+EPEogYcCj63OToKWaIHM/IpIzVNBKYg1EPK0DjgE9mTxy1yOu7+wXQAEMqEKIPx3il80srpavL0C9X5lZJFXDseGKRgmEfRY8uRVPq8oLOoes4uyKul31DAoXNAja+tXSlhGKXQiqxMkGbyg=,iv:pkofZVOp3fBdyhhSyFwQOBgCvQGl2NWl8DMkESibbV0=,tag:unJFi8g/7anVVkZPo8QpaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
