home_wifi_network_password: ENC[AES256_GCM,data:3r4jHN7rfyf4pu/PKh9z2xAQ,iv:MT9rrcVphnc7JCgwAKtMvW+NtETkx1F5Rs7h/xNXBB4=,tag:VgVSoGKJ7NbSNjRrwWfGEA==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:C3prqyjpuRPbkRb8pftUDUsynp906KmGNsg13Ti0Xsm/8T0pMaBJKF+XHa0dCTsoSNhnAAMIPN4=,iv:8oUFdYtx6S2nZJ4LPT4d/DTVEO/L8GV+savBHX9ZpkU=,tag:KM0y6jiLuYZGn3iZeR4DZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r68wyfhzkpkm9j2jwyg0vfud4qds3a74x7qkfgk39mv5q758lfjqwnu4nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSlNvNlNQYmJhSFJsR2xt
            NWlpNWY1REYrMWRYSnpmWFZmcWxpV0NrL3lVCldSWkVlZVJjbHFOeVlCQUR0a2Zq
            MTA1RkxjNktrRHNXNHFQU3Vldy9RblUKLS0tIFJVOXVtYlVON1puUFo1Q3JvK1gx
            b3ZIRFNkNnMzZmtJYSthSC8vQ0tHanMKTvbFuNa4gAGAh7ss7TqGQ4klEAZRRfgz
            9ryUfWLscTWCSmjM6QFzdowNW6Bcu8RHQqvUE2jF5cnl01x/4OxXfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age173gaqk56n79pf0yhq7t6rh3k6c279xjqu6zywthzksjdp9kzfgts9pz20u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVWQ5Y0l1TzFBZzFoWGdu
            eTRMejF6cFNMNXVWOUVKNkplMGtlWVh1cVhvCk5WWGVTZHBXMkpnaWI2cm44a0hD
            TlBOK2FOU2g0aU1uVUhJK1FGYnoxOTgKLS0tIHJlUkcwMDBMb050TEg1cVpqbkJZ
            VmJZOWNxZ25XVmZlcTdQOFZJdUFUeWcKCAKpGocgIXWgnmghb1uvdtFXuJPr+MZX
            Z17RAZw6DZBOjkq+NRLdbEDdAtxJfhmv9S/aVQVCrafti0O2ekc30g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10zq729g0z50ln4v2c3l5msk0zpxwe2pe62ayyz9ht5y9ah6zfd4slcynec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWlhlZFRFYU5BMnZlMjdC
            a1lXK3RpOXpoam8vYU9ZS3JNUEpHU1pBVlM0CjZMTEtISGJZbXNuOGxMUE1jQnhi
            ZGcwU1VDNDM5eHRTOTloekMrSzVvSmcKLS0tIExDanEwSG02NlFYK1laZVcxdWpo
            YjA3Y0hsQ05kREM3bDF6T2tKRGdpUDAKSb4n1l/fw/SEgA8cA9giDnDwzY1/A/4t
            UICh0wtsDoZCh7K9/lJn7WYhd7qit8OYGMet7hipqTcll97NUO03tQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wyp0qkl493emy03h9dng9q5mtjhrzecuwlkcss6q8rsev6fmw53sct8r4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRnNkcUVJSmFmdnRhdUlB
            OVI0SDhuQnRKSXVFdXNRc2oyN2F3OEdieWhRCmw5R0sydmFUWkJhZkpxME5rUVN3
            UWZMWnNCdEcvSCs1T1hlOVk0aVBRTTQKLS0tIEd1NmJsV0VmeW9mNkhoRUtLdllN
            YUVTOVZGTE5za0tESVF0OFRRcXpMQTgK0s+p7dNwa8NxL3jVpfGxGcx2LKMTnHaz
            fo4c2pm79alQblYBdtmEKDdrpog8emUbssd07foeg2Fh7KpwOO5KXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T20:02:49Z"
    mac: ENC[AES256_GCM,data:nPFhslGqhg6qn3FMqzBQkbfyi9PxMVgaIxQDGBzlayH83u/s8iuaqzG2uBEaQFule0o2q15U5tkLaTyTWRWal0qvt3vvw9MDgIhb0GNLto6GJ1dXZM3PcBAo0ofMWkflB6/ZdRB/AFNzRg8AzpX+vwvWfR1wPVwwM2c85XGwRjg=,iv:BbtQ1SkksOkhmEdGVONLOfnPS1DfvBRgoatzBBBQSmY=,tag:6thq8me/9a7SMVaQtYYxQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
